### ISSUE TITLE
Ecommerce tracking

### ISSUE THREAD

**Issue by Hamidkhanswb** [donni106/matomo-tracker-react-native#10]
Hey, i could not found the ecommerce traking in docs so kindly include it as soon as possible because without it, our goal is incomplete according to the current running project.
Thanks

**Comment by donni106** [comment]
Hi @Hamidkhanswb, i will look into it. Can you link me some Matomo docs concerning that ecommerce tracking so that I can work with it? Thanks.

**Comment by donni106** [comment]
Hi @Hamidkhanswb, can you please elaborate on this one?
