### ISSUE TITLE
Problem on merging signed out users when the user id (uid) is undefined

### ISSUE THREAD

**Issue by BatDroid** [donni106/matomo-tracker-react-native#15]
**Describe the bug**

I have an application on which user gets logged out frequently. After entrance user gets logged in immediately. I want things like `AppStart` and events before logging in be merged with the user id which has been after that.
As far as I remember Matomo did that based on the ip address of the user but recently the problem is that I'm facing is that all of my users, when they are logged out, their events are considered as one single visitor which is `undefined`(or `null` if I pass that).

<img width="418" alt="Screenshot 2023-03-03 at 2 24 54 PM" src="https://user-images.githubusercontent.com/10198892/222777409-6c3fd8e4-4afc-413e-8030-6de6a03a6ff6.png">

I looked over this issue and reached to [this link](https://github.com/matomo-org/matomo/issues/16949#issuecomment-744735786) applied what is suggested but still have the issue unless I comment [this line of code](https://github.com/donni106/matomo-tracker-react-native/blob/09b9b49d59ad6b493d041d3807809f6ba41860a3/src/MatomoTracker.js#L178) the issue is fixed. I know that i's not a good solution to remove it but maybe it can be changed to something like this:

```js
...(this.userId ? {uid: this.userId}: {}),
```
I'll make a PR for that so that if you wanted it can be merged, otherwise I guess I'll need to use my forked repo for that.

thank you in advance

**Comment by donni106** [comment]
Thanks for the description and opening an issue. With quick read it sounds quite well and the code change makes sense to me. I am looking forward to merge and include it soon!
