### ISSUE TITLE
Option for log custom dimension

### ISSUE THREAD

**Issue by venkatprabu711998** [donni106/matomo-tracker-react-native#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by donni106** [comment]
hi @venkatprabu711998, thanks for opening an issue, but it seems that your description isn't there.

**Comment by donni106** [comment]
The new issue #19 from @karthik-hr seems to be the same request and I have answered there.
