### ISSUE TITLE
Automatically send device information

### ISSUE THREAD

**Issue by angelxmoreno** [donni106/matomo-tracker-react-native#3]
It would be phenomenal if this module would send device information from the `expo-devices` or `expo-constants` modules along with the tracking events.

I am unable to find where i can set my device type.
 
Looking at https://developer.matomo.org/api-reference/tracking-api#optional-user-info it seems like this "extra" information can be set as custom variables (https://matomo.org/docs/custom-variables/).

**Comment by donni106** [comment]
Thanks @angelxmoreno, it is a good point. I already thought about it, because it is a common feature. Let us see, how we can manage it. This is definitely possible.

**Comment by KarlaSaenz** [comment]
+1   Please add is feature

**Comment by donni106** [comment]
@angelxmoreno @KarlaSaenz which data from [expo-device](https://docs.expo.io/versions/latest/sdk/device/), [expo-constants](https://docs.expo.io/versions/latest/sdk/constants/) and/or [react native dimensions](https://docs.expo.io/versions/latest/react-native/dimensions/) could you think of having with the matomo tracking as [optional user info](https://developer.matomo.org/api-reference/tracking-api#optional-user-info)?

I think the device brand and model name can be useful as well as the resolution of the device the visitor is using. These could be a first step.

**Comment by angelxmoreno** [comment]
I'll get a list out with sample values

**Comment by donni106** [comment]
I have opened a PR which allows passing additional optional user info params! This will be released in version 0.3.0 soon.

**Comment by donni106** [comment]
0.3.0 is available now!
