### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by oanacioara** [donni106/matomo-tracker-react-native#7]
I get a compilation error when running my unit tests with Jest.

/path/to/node_modules/matomo-tracker-react-native/index.js:1
    import MatomoTracker from './src/MatomoTracker';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at compileFunction (<anonymous>)

Versions:
"matomo-tracker-react-native": "^0.2.4",
"jest-expo": "^42.0.0",
"jest-junit": "^12.1.0",

**Comment by donni106** [comment]
You need to add the package to the jest config `transformIgnorePatterns`. Do you need an example how to do this?

**Comment by oanacioara** [comment]
I would appreciate it. Thank you!

**Comment by oanacioara** [comment]
Tried this in my `jest.config.js`

```
module.exports = {
  transformIgnorePatterns: ['/node_modules/matomo-tracker-react-native'],
};
```

and now I get

```
ReferenceError: __DEV__ is not defined

    > 1 | import { Text, View } from 'react-native';
        | ^
      2 | import * as React from 'react';
```

**Comment by donni106** [comment]
Have you created your instance with `__DEV__` values like in the Readme.md?

```
  disabled: __DEV__, // optional, default value: false. Disables all tracking operations if set to true.
  log: __DEV__  // optional, default value: false. Enables some logs if set to true.
```

Please set them explicitly to true or false or remove them to use the default values. `__DEV__` seems to not work in your environment. I could see if i find the time to add a paragraph to the readme, when to be able to use that global `__DEV__`.

**Comment by oanacioara** [comment]
I don't have it in my source code, it is coming from react dependencies. The error shows the `react-native` import as having the issue.

I also tried configuring jest in my `packag.json` like so:

```
"jest": {
    "preset": "jest-expo",
    "reporters": [
      "default",
      "jest-junit"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "**/*.{ts,tsx}",
      "!**/coverage/**",
      "!**/node_modules/**",
      "!**/babel.config.js",
      "!**/jest.setup.js"
    ],
    "transformIgnorePatterns": ["/node_modules/matomo-tracker-react-native/"]
  }
```
but this has no effect. I still get the original syntax error.

**Comment by donni106** [comment]
Can you have a look here please: https://stackoverflow.com/questions/37487492/react-native-dev-is-not-defined
Does something help. Do you have a babel config file?

**Comment by donni106** [comment]
I use `babel-preset-expo` in the babel config.

**Comment by oanacioara** [comment]
Thanks for all your help with this! We have decided to do our custom implementation for this because we need to be able to send custom data and device info.

**Comment by donni106** [comment]
Which i made available these days with this PR: https://github.com/donni106/matomo-tracker-react-native/pull/6
It will be merged this week.
You are welcome to try this out.

**Comment by donni106** [comment]
@oanacioara how did you proceed now? 0.3.0 with ability for custom data is available now!
